### PR TITLE
Fixes rename servlet name and report title for collection items hits/downloads statistics. damspas#265

### PR DESCRIPTION
**Pull request by lsitu**
Related: https://github.com/ucsdlib/damspas/issues/265
Suggested by Gabriela, I am creating the PR to rename the servlet to statsCollectionObjects.do and the report title to "Object/Collection Hits by Month" and "Object/Collection Downloads by Month" for collection items hits/downloads statistics.

### CODE REVIEW

**Comment by mcritchlow** [comment]
👍

**Comment by lsitu** [comment]
Thanks @mcritchlow .

**Comment by gamontoya** [comment]
@lsitu Matt Peters said the title should be only object (not title). Can you change that still?

From:
"Object/Collection Hits by Month" and "Object/Collection Downloads by Month"

To:
"DAMS Object Hits by Month" and "DAMD Object Downloads by Month"

**Comment by lsitu** [comment]
@mcritchlow, @gamontoya I've created another PR https://github.com/ucsdlib/damsmanager/pull/125 to rename the report title to "DAMS Object Hits by Month" and "DAMD Object Downloads by Month" respectively. It's ready for review now.

**Comment by gamontoya** [comment]
@lsitu I hope you didn't take my typo literally: DAMS and not **DAMD**

**Comment by lsitu** [comment]
@gamontoya I've corrected that typo the the PR.

**Comment by gamontoya** [comment]
@lsitu Thank you.

**Pull request merged**
