### PR TITLE
Fixes #301 - Add support to export metadata in RDF and CSV format for single items and collections

### LINKED ISSUE #301: Support batch export metadata in RDF and CSV format
### Descriptive summary

Batch export metadata in CSV and RDF format with an ARK list or objects in a collection.

### Rationale

To support Batch edit in https://github.com/ucsdlib/damsmanager/issues/263, we need to tool to export metadata in CSV format. The tool should be able to export metadata provided by a list of ARKs, or objects/ARKs in any collection(s).

### Related work

https://github.com/ucsdlib/damsmanager/issues/263

### PR DESCRIPTION
**Pull request by lsitu**
Fixes #301

#### Local Checklist
- [ ] Tests written and passing locally?
- [x] Code style checked?
- [x] QA-ed locally?
- [x] Rebased with `master` branch?
- [ ] Configuration updated (if needed)?
- [ ] Documentation updated (if needed)?

#### What does this PR do?
Add support to export metadata in RDF and CSV format for single items and batch of collections.

##### Why are we doing this? Any context of related work?
References #301, #263 

#### Screenshots
screen shot 2019-01-11 at 1 33 07 pm

screen shot 2019-01-14 at 12 11 18 pm

screen shot 2019-01-11 at 2 12 17 pm

screen shot 2019-01-11 at 2 10 35 pm

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by mcritchlow** [comment]
It's unclear to me from the referenced ticket if RDF export was part of the requirements. Could you point to me where that's called out? Is that something that was built for developers, or DOMM? Just want to make sure a) the feature is desired and b) it won't cause any confusion about the 'correct' way of doing things is.

**Comment by lsitu** [comment]
@mcritchlow I think RDF is s format I added in as a convenient tool for our devs since I see often we need this tool to export the metadata in the ARK list for report and/or update purpose. Yes, we can remove it if this will confuse DDOM users. Just let me know your thoughts. Thanks.

**Comment by mcritchlow** [comment]
@lsitu - I see, OK. I think this seems like a really nice proposal, I'm just not seeing a spec/requirements that this has been made against. So I'm going to copy @arwenhutt here so she can take a look at your screenshots and maybe help us get a sense if this is what we're after. Thanks!

**Comment by mcritchlow** [comment]
@lsitu - Oh would you also mind attaching an example of a single collections exported in CSV format? I suspect that might Arwen for evaluation

**Comment by lsitu** [comment]
@mcritchlow / @arwenhutt I just added another screenshot (the second one) to the descriptions above for exporting metadata with a list of arks uploaded in a file.

**Comment by arwenhutt** [comment]
@lsitu can you attach an example csv export file?

**Comment by lsitu** [comment]
@mcritchlow / @arwenhutt Attached is the example CSV export for dataMares: Fisheries collection (w/o components):
CSV export for dataMares: Fisheries
Exclude components:
[batchExport-dataMaresFisheries.csv.txt](https://github.com/ucsdlib/damsmanager/files/2756976/batchExport-dataMaresFisheries.csv.txt)

Include components:
[batchExport-dataMaresFisheries-components.csv.txt](https://github.com/ucsdlib/damsmanager/files/2756981/batchExport-dataMaresFisheries-components.csv.txt)

**Comment by arwenhutt** [comment]
Thanks @lsitu !
@GregReser and I have been working on a draft spec for #263 including requirements for batch export.  There's a lot of overlap with what you've done here.   @GregReser and I will finish up the requirements we've been working on for the batch export, add those to issue #301, and also provide some review on the initial export sample.

**Comment by lsitu** [comment]
@mcritchlow / @arwenhutt I've added commit https://github.com/ucsdlib/damsmanager/pull/302/commits/cf6ca22f25e0d6ccf3d3a18681cec8059372935a above for the CSV Export function basing on the spec and the review comments. Here is the CSV exported for dataMares: Fisheries collection:
[batchExport-dataMaresFisheries.updated.csv.txt](https://github.com/ucsdlib/damsmanager/files/2788825/batchExport-dataMaresFisheries.updated.csv.txt)
Could you review it again? Thanks.

**Comment by GregReser** [comment]
@lsitu some notes on the CSV exported for dataMares: Fisheries collection:
batchExport-dataMaresFisheries.updated.csv.txt

There is still an issue with newlines in bb6793765b and bb7511362r
When importing to Excel, these result in part of the Note:description value being forced to a new row.
- bb6793765b
  - newline before "This citation was formerly: Giron-Nava, Alfredo (2016):"
- bb7511362r
  - newline before "Responsable Administrativo. Lic. Marisol Plascencia de la Cruz""

I'm also getting some complications parsing the CSV into Excel, where a comma in the note value is being parsed as a new column.
- bb6793765b
  - ...Giron-Nava, Alfredo (2016)... is split into two columns at the comma

I wonder if using tab separators would be more reliable.

image

**Comment by lsitu** [comment]
@GregReser I think you close the PR by mistake. I am reopening it now. IIt won't work with the Tab seperate format since there are new lines/linefeeds in the the description text.
What tool are you use to parse the CSV file? I rename it to batchExport-dataMaresFisheries-components.csv and double click to open it by Excel, I don't see the problem. So I believe the encoding with CSV should work.

**Comment by GregReser** [comment]
@lsitu I was using the Excel data import from text wizard, mostly so I could set the encoding to UTF-8.  If I open the .csv file directly to Excel, the encoding is off, e.g.,  MascareÃ±as-Osorio, Ismael@bb5770728n

This is probably just a workflow thing.  I need to sort out how to open the .csv in a spreadsheet and get the right parsing, encoding and cell format.

**Comment by GregReser** [comment]
@lsitu would it be possible to keep Begin date and End date nest to each other and have them placed after the other date strings?
In the case of the dataMares export, it would be:

Date:collected
Date:creation
Date:issued
Begin date
End date

**Comment by GregReser** [comment]
@lsitu it would be better if the Collection(s) column was placed after the standard columns.  It could go before the copyright column.
The idea would be to have all the standard template columns first, and any extra columns for this export after them.

**Comment by lsitu** [comment]
@GregReser Okay. I'll see how to make these specific field orders for you.

**Comment by GregReser** [comment]
@lsitu The export looks very good.  All the data is included and the column headers match the Excel import template.
If you are going to run another test, try this object that contains all the properties in the ingest template:
https://librarytest.ucsd.edu/dc/object/bb2322475s

**Comment by lsitu** [comment]
@GregReser I'll correct the format for RelatedResource. And I'll make the fields order changes as you suggested for you. For the `Collection(s)` header, Could I use the lower case header `collection(s)`? This will help to group it with those headers for copyrights. Thanks.

**Comment by GregReser** [comment]
@lsitu yes, collection(s) is fine.

**Comment by GregReser** [comment]
@lsitu Looking at related resource made me think about how we format the @ separator.  We should be consistent with it everywhere.  Since we use " @ " in related resource, let's do the same thing in the exported linked records - label @ ark

Sorry to change this, but it's better to do it now.

**Comment by lsitu** [comment]
@GregReser / @mcritchlow I've added commit https://github.com/ucsdlib/damsmanager/pull/302/commits/c81dae3e8f1ccc56eb899756060fb17c981e2e61 to make the desired header output order you want and corrected the formats for RelatedResouce. Here are the exports for example https://librarytest.ucsd.edu/dc/object/bb2322475s and the dataMaresFisheries collection:
[batchExport-bb2322475s.csv.txt](https://github.com/ucsdlib/damsmanager/files/2823297/batchExport-bb2322475s.csv.txt)
[batchExport-dataMaresFisheries-v2.csv.txt](https://github.com/ucsdlib/damsmanager/files/2823299/batchExport-dataMaresFisheries-v2.csv.txt)
 Could you review the export result again? Thanks.

**Comment by GregReser** [comment]
@lsitu the new tests look very good! It looks all the column headers match the import template and no data was lost.

Before closing this ticket and moving on to the batch edit specification, I want to make sure that we include an export option for .xlsx output in addition to .csv (and that .csv output is formatted as UTF-8-BOM and ends with .csv not .csv.txt)

In working with the text .csv files here, I found the process to create a spreadsheet with correct linefeed, character encoding and date as text formatting was very time consuming.  Opening the file directly to Excel or using the data import wizard required extra conversion steps.  Since we will be editing and re-importing metadata with Excel, we should make the workflow as direct as possible, not just to save time, but to avoid formatting errors.

We should also have the option to export .csv for use in OpenRefine or other applications.

**Comment by lsitu** [comment]
@GregReser Yes, the filename of the CSV output format will be ended with .csv. And no problem, I'll add the option for Excel .xlsx output for you.

**Comment by lsitu** [comment]
@mcritchlow / @GregReser I've added a commit to support Excel format output as the default option (see commit https://github.com/ucsdlib/damsmanager/commit/67cf0209902648b5b921b66e5051aa6737125209 above). Here are the export results for example https://librarytest.ucsd.edu/dc/object/bb2322475s and the dataMaresFisheries collection:
[batchExport-bb2322475s.xlsx.txt](https://github.com/ucsdlib/damsmanager/files/2834358/batchExport-bb2322475s.xlsx.txt)
[batchExport-dataMaresFisheries.xlsx.txt](https://github.com/ucsdlib/damsmanager/files/2834359/batchExport-dataMaresFisheries.xlsx.txt)
Please remove suffix `.txt` to open it with Excel. The codes are ready for review now. Thanks.

**Comment by lsitu** [comment]
@mcritchlow / @GregReser Have you got a chance to review PR with the output attached? Thanks.

**Comment by mcritchlow** [comment]
@lsitu - i reviewed the commit a while ago. But waiting on any merging until Greg reports back on the output

**Comment by lsitu** [comment]
Thanks @mcritchlow. @GregReser Do you need any changes to the CSV and Excel outputs?

**Comment by GregReser** [comment]
@lsitu this looks great, just two changes:

dams:Note @ type "statement of responsibility" was exported as "Statement of Responsibility"
It should be "Note:statement of responsibility"

Please add dams:Note @ type "local attribution" to the export.  The column name should be: 
"Note:local attribution"
Even though this is not in the current Excel ingest template, we may need to edit it in the batch edit tool (for example, if we have to change attribution from DLDP to SC&A)

**Comment by jessicahilt** [comment]
Can we take a look at this ticket this week?

**Comment by lsitu** [comment]
@jessicahilt Sure. I'll add the examples for bb2322475s and the dataMares collection so that @GregReser can review it again.

**Comment by lsitu** [comment]
@GregReser / @mcritchlow Here is the examples exported from the latest commit above:
[batchExport-bb2322475s.xlsx.txt](https://github.com/ucsdlib/damsmanager/files/2932685/batchExport-bb2322475s.xlsx.txt)
[batchExport-dataMaresFisheries.xlsx.txt](https://github.com/ucsdlib/damsmanager/files/2932687/batchExport-dataMaresFisheries.xlsx.txt)

**Comment by GregReser** [comment]
@lsitu the new examples look good, all columns and values are what I expect.
Once this is working in DAMS Manager, will the output files still end with ".xlsx.txt"?

**Comment by lsitu** [comment]
@GregReser The output file will be ended with ".xlsx" for Excel. I just renamed it to .txt so that I can attached it here for you to review.
@mcritchlow I think codes for PR#302 is ready for you to review now. Thanks.

**Pull request merged**
