### PR TITLE
Fixes #251 - Retain LF and CR control characters.

### LINKED ISSUE #251: Ignore or escape control characters upon metadata validation
### Descriptive summary

When the metadata source contains a control character (example "[end-of-text](https://www.fileformat.info/info/unicode/char/0003/index.htm)" as '`\3`'), the metadata passes the RDF/XML validation in the report, yet fails on the server side with an error such as: 
`com.hp.hpl.jena.shared.CannotEncodeCharacterException: cannot encode (char)  ETX in context XML` 

### Rationale

It can take a long time to examine which characters are special and will cause these errors, so it'd be great if the system can highlight or even ignore these characters

### Expected behavior
System will ignore or escape the control characters, and/or report the error to a metadata analyst via the RDF/XML validation reports

### Actual behavior
The system raises no error in reports, but silently fails and does not show the object. Example: https://librarytest.ucsd.edu/dc/object/bd9611798m 

### Related work

#250

### PR DESCRIPTION
**Pull request by lsitu**
Fixes #251 

#### Local Checklist
- [x] Tests written and passing locally?
- [x] Code style checked?
- [x] QA-ed locally?
- [x] Rebased with `master` branch?
- [ ] Configuration updated (if needed)?
- [ ] Documentation updated (if needed)?

#### What does this PR do?
Don't ignore control characters Line Feed and Carriage Return.

##### Why are we doing this? Any context of related work?
References #251

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by lsitu** [comment]
@ucsdlib/developers Can anyone review and merge the PR while @mcritchlow is out? Thanks.

**Comment by VivianChu** [comment]
@lsitu - There's merge conflict for this branch.  Could you take a look?  Thanks

**Comment by lsitu** [comment]
@VivianChu I've fixed the conflicts. Thanks.

**Comment by lsitu** [comment]
Thanks @VivianChu.

**Pull request merged**
