### PR TITLE
Fixes damspas#360 - Update local attribution note for objects referencing DLDP.

### PR DESCRIPTION
**Pull request by lsitu**
Fixes https://github.com/ucsdlib/damspas/issues/360

Update local attribution note for objects referencing DLDP.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by lsitu** [comment]
@mcritchlow I think this should be @gamontoya's call. The URLs are request in https://github.com/ucsdlib/damspas/issues/360. It looks like these URls are external that may not affect DAMS page loading behavior that can be fully controlled by redirect. And we may need to update all the local attribution notes to use https for consistency if we decide to do that.

**Comment by gamontoya** [comment]
@lsitu Although these alias URLs use **http**, I think they're fine to keep as is. @mcritchlow Is there a reason you feel they need to be **https**?

**Comment by mcritchlow** [comment]
@gamontoya - Because in general we're trying to move all our URL base to https. Many browsers will now complain/flag URLs that are http as "insecure". So it's trying to mitigate that.

@jhriv - Can the `yourls` app handle `https` links?

**Comment by lsitu** [comment]
@gamontoya What do think think regarding changing the DLCP links to use https instead of http as @mcritchlow suggested? We may need to update ticket https://github.com/ucsdlib/damspas/issues/360 to reflect it and do another round of update for the local attribution notes if we need to move forward with https. Thanks.

**Comment by gamontoya** [comment]
@lsitu @mcritchlow I was waiting to hear back from @jhriv if the yourls app accept https links before updating the request and ticket.

**Comment by gamontoya** [comment]
@lsitu @mcritchlow Confirming that the yourls app accepts https. I'll update the previous ticket.

**Comment by lsitu** [comment]
Thanks @gamontoya.
@mcritchlow I've updated it to use https. See commithttps://github.com/ucsdlib/damsmanager/pull/191/commits/bda509ac175f6d115c1030c6b7d4b7474af7cf9d.

**Comment by lsitu** [comment]
@gamontoya @mcritchlow Do we want a new release for damamanager? In addition to this one, we also got a couple more commits from the sprint before last.

**Comment by mcritchlow** [comment]
@lsitu - yes, I'd say feel free to move ahead with a release 👍

**Comment by lsitu** [comment]
@gamontoya @mcritchlow Okay. I've created the release ticket: https://github.com/ucsdlib/damsmanager/issues/193.

**Pull request merged**
