### PR TITLE
Fixes damsrepo#49 - Catch and report the failed result for SOLR index.

### PR DESCRIPTION
**Pull request by lsitu**
Fixes damsrepo#49 ; refs https://github.com/ucsdlib/damsrepo/issues/49

Catch the failed status for SOLR index.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by mcritchlow** [comment]
So the outcome of this PR is that end-users (curators) will now get properly notified if an index attempt for a record fails, whereas before they were not? Is that right?

**Comment by lsitu** [comment]
Yes. However it's not the final index status but the failure status of any records that are failed to be added to the ActiveMQ queue, while it's always successfully previously though the failure messages be showing up on the status bar.

**Comment by mcritchlow** [comment]
Ok, so is the [output from these lines](https://github.com/ucsdlib/damsmanager/blob/cd24c168624b0d69319e093297852f0f13cfaa4b/src/edu/ucsd/library/xdre/collection/SOLRIndexHandler.java#L181-L183) a little misleading then? Should it instead say something more specific about the interaction with ActiveMQ (successfully queued for Solr indexing/unsuccessfully queued for Solr indexing, for example) instead of saying Solr directly?

**Comment by lsitu** [comment]
@mcritchlow: Good catch! Thanks. I've updated the report messages, see https://github.com/ucsdlib/damsmanager/pull/149/commits/eb946f91d6d75f1aee0c8845966f17cb265b7b4c above.

**Comment by mcritchlow** [comment]
LGTM! Thanks @lsitu!

**Pull request merged**
