### PR TITLE
Fixes removing direct ingest from MARC/MODS Import tool. #116

### PR DESCRIPTION
**Pull request by lsitu**
Related: https://github.com/ucsdlib/damsmanager/issues/116

### CODE REVIEW

**Comment by mcritchlow** [comment]
@lsitu would you mind attaching a screenshot of what this looks like on your machine using the changes you've made? I see you're hiding the core ingest parts of the page/form, but I'm curious how that will present to the user. We could probably have @GregReser take a quick look and provide any feedback.

**Comment by lsitu** [comment]
@mcritchlow Here is the screenshot for the MARC/MODS Ingest form after applying the changes in the PR:
screen shot 2017-01-11 at 8 50 32 am

**Comment by mcritchlow** [comment]
Great, thanks @lsitu. Looks good to me and matches @GregReser's screenshot.

**Comment by lsitu** [comment]
@mcritchlow Sorry I think I had better reverted it to avoid the conflicting of the hotfix in the current release.

**Pull request merged**
