### PR TITLE
Updated for FAST support for authority records lookup. #104

### PR DESCRIPTION
**Pull request by lsitu**

### CODE REVIEW

**Comment by mcritchlow** [comment]
I think this looks like it follows the logic from @GregReser. It's admittedly a bit hard without having unit tests. But, we'll have Greg test and verify the different conditions. Thanks @lsitu 👍

**Comment by lsitu** [comment]
Thanks @mcritchlow . I just deployed it to staging for Greg to test.

**Comment by GregReser** [comment]
@lsitu @mcritchlow Tested in staging and everything looks good.

**Comment by lsitu** [comment]
Thanks @GregReser.

**Pull request merged**
